name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install compile tools
      run: |
          sudo apt update -y
          sudo apt install -y make g++ valgrind
    - name: make test
      run: make test
    - name: make valgrind
      run: make valgrind
