name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install compile tools
      run: |
          sudo apt update -y
          sudo apt install -y make g++ valgrind
    - name: Run all tests
      run: make test
    - name: Run M1
      run: make m1
    - name: Run M4
      run: make m4
    - name: Valgrind all tests
      run: |
          make valgrind
          make valgrind-m1
          make valgrind-m4
