name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install compile tools
      run: |
          sudo apt update -y
          sudo apt install -y make g++ valgrind
    - name: Run tests
      run: make test-all
    - name: Valgrind tests
      run: make valgrind-all
